# Generated by Django 3.1.6 on 2021-04-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210423_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-view_date'], 'verbose_name': 'новинку', 'verbose_name_plural': 'новинки'},
        ),
        migrations.AlterModelOptions(
            name='newstranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'новинку Translation'},
        ),
        migrations.AlterField(
            model_name='news',
            name='view_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
    ]
