# Generated by Django 3.1.4 on 2021-01-04 20:10

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=256)),
                ('position', models.CharField(choices=[('HEADER_TOP', 'header_top'), ('HEADER_BOTTOM', 'header_bottom'), ('DEFAULT_TOP', 'default_top'), ('DEFAULT_BOTTOM', 'default_bottom'), ('FOOTER_TOP', 'footer_top'), ('FOOTER_BOTTOM', 'footer_bottom')], default='DEFAULT_TOP', max_length=32)),
                ('enable', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='date modified')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContentTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('data', models.TextField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.content')),
            ],
            options={
                'verbose_name': 'content Translation',
                'db_table': 'content_content_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
