# Generated by Django 3.1.4 on 2021-01-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default='test', max_length=256, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='Показывать'),
        ),
        migrations.AlterField(
            model_name='content',
            name='position',
            field=models.CharField(choices=[('HEADER_TOP', 'header_top'), ('HEADER_BOTTOM', 'header_bottom'), ('DEFAULT_TOP', 'default_top'), ('DEFAULT_BOTTOM', 'default_bottom'), ('FOOTER_TOP', 'footer_top'), ('FOOTER_BOTTOM', 'footer_bottom')], default='DEFAULT_TOP', max_length=32, verbose_name='позиция'),
        ),
        migrations.AlterField(
            model_name='content',
            name='route',
            field=models.CharField(max_length=256, verbose_name='Путь'),
        ),
    ]
