# Generated by Django 3.1.4 on 2021-01-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='full_name',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
