# Generated by Django 3.1.4 on 2021-01-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210104_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
