# Generated by Django 3.1.4 on 2021-01-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_tag_tagtranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='pk_name',
            field=models.TextField(default='123', unique=True),
            preserve_default=False,
        ),
    ]
