# Generated by Django 3.1.4 on 2021-01-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_tag_pk_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='pk_name',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='tagtranslation',
            name='name',
            field=models.TextField(blank=True, unique=True, verbose_name='Название'),
        ),
    ]
