# Generated by Django 3.1.4 on 2021-01-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210126_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='code',
            field=models.CharField(max_length=128, unique=True, verbose_name='Код'),
        ),
    ]
