# Generated by Django 3.1.4 on 2021-01-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210126_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='products',
        ),
        migrations.AddField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(null=True, related_name='tags', to='shop.Product', verbose_name='Теги'),
        ),
    ]
