# Generated by Django 3.1.4 on 2021-01-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210126_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='products', to='shop.Tag', verbose_name='Теги'),
        ),
    ]
