# Generated by Django 3.1.4 on 2021-01-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210126_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='glow_in_the_dark',
            field=models.BooleanField(default=True, verbose_name='Светится в темноте'),
        ),
        migrations.AddField(
            model_name='product',
            name='glow_in_the_uv',
            field=models.BooleanField(default=True, verbose_name='Светится в ультрафиолете'),
        ),
        migrations.AddField(
            model_name='product',
            name='hit',
            field=models.BooleanField(default=False, verbose_name='Хит'),
        ),
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=True, verbose_name='Новинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='shop.Tag', verbose_name='Теги'),
        ),
    ]
