# Generated by Django 3.1.4 on 2021-01-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210127_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='code',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='BrandTranslation',
        ),
    ]
