# Generated by Django 3.1.4 on 2021-01-27 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210127_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.BooleanField(default=False, verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='category',
            name='full_name',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='path',
            field=models.CharField(blank=True, max_length=256, verbose_name='Путь'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Имя'),
        ),
    ]
