# Generated by Django 3.1.4 on 2021-01-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210127_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.Tag', verbose_name='Теги'),
        ),
    ]
