# Generated by Django 3.1.4 on 2021-01-30 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20210130_1038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagTranslation',
        ),
    ]
