# Generated by Django 3.1.4 on 2021-01-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.Color', verbose_name='Цвета'),
        ),
    ]
