# Generated by Django 3.1.4 on 2021-02-02 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='media_files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='shop.mediafile', verbose_name='Медиафайлы'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumnail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumnail', to='shop.mediafile', verbose_name='Превью'),
        ),
    ]
