# Generated by Django 3.1.4 on 2021-02-02 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20210202_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media_files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_media_files', to='shop.mediafile', verbose_name='Медиафайлы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_thumnail', to='shop.mediafile', verbose_name='Превью'),
        ),
    ]
