# Generated by Django 3.1.6 on 2021-02-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20210202_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_count',
            field=models.IntegerField(default=0, verbose_name='Остаток'),
            preserve_default=False,
        ),
    ]
