# Generated by Django 3.1.6 on 2021-03-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_product_total_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='path',
            field=models.CharField(blank=True, max_length=256, unique=True, verbose_name='Путь'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='media_files',
        ),
        migrations.AddField(
            model_name='product',
            name='media_files',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_media_files', to='shop.MediaFile', verbose_name='Медиафайлы'),
        ),
    ]
