# Generated by Django 3.1.6 on 2021-04-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20210428_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='myprice',
        ),
        migrations.AddField(
            model_name='product',
            name='price_opt_1',
            field=models.IntegerField(default=0, verbose_name='Опт от 11000'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_opt_2',
            field=models.IntegerField(default=0, verbose_name='Опт от 30000'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_opt_3',
            field=models.IntegerField(default=0, verbose_name='Опт от 70000'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_opt_4',
            field=models.IntegerField(default=0, verbose_name='Опт от 110000'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_opt_m',
            field=models.IntegerField(default=0, verbose_name='Мелкий Опт'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_ret',
            field=models.IntegerField(default=0, verbose_name='Розничная цена'),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
