# Generated by Django 3.1.6 on 2021-04-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20210428_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_2xl',
            field=models.IntegerField(default=0, verbose_name='2XL размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_3xl',
            field=models.IntegerField(default=0, verbose_name='3XL размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_4xl',
            field=models.IntegerField(default=0, verbose_name='4XL размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_l',
            field=models.IntegerField(default=0, verbose_name='L размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_m',
            field=models.IntegerField(default=0, verbose_name='M размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ns',
            field=models.IntegerField(default=0, verbose_name='Без размера'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_s',
            field=models.IntegerField(default=0, verbose_name='S размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_xl',
            field=models.IntegerField(default=0, verbose_name='XL размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_xs',
            field=models.IntegerField(default=0, verbose_name='XS размер'),
        ),
    ]
