# Generated by Django 3.1.6 on 2021-06-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_2xs',
            field=models.IntegerField(default=0, verbose_name='2XS размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_3xs',
            field=models.IntegerField(default=0, verbose_name='3XS размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_4xs',
            field=models.IntegerField(default=0, verbose_name='4XS размер'),
        ),
    ]
