# Generated by Django 3.1.6 on 2021-07-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20210627_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sex',
            field=models.CharField(choices=[('Men', 'Мужское'), ('Woman', 'Женское'), ('Kids', 'Детское'), ('Unisex', 'Унисекс')], default='Men', max_length=10),
        ),
    ]
