# Generated by Django 3.1.6 on 2021-08-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20210717_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_count',
            field=models.IntegerField(default=0, verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='content',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Состав'),
        ),
    ]
