# Generated by Django 3.1.6 on 2021-08-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20210815_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors_en',
            field=models.ManyToManyField(blank=True, related_name='products_en', to='shop.Color', verbose_name='Цвета_En'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags_en',
            field=models.ManyToManyField(blank=True, related_name='products_en', to='shop.Tag', verbose_name='Теги_En'),
        ),
    ]
